version: '3.8'

services:
  api:
    container_name: API_Gateway
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - JWT_SECRET=4f358876d1128516c0b6e29e026fe14ee47300f54bbdc440a7eab415cfafd03a6c8b47f582ccd297ea765a2c666770680b9fcb573557912c1f63680e7956de2816e7f8689f6268fb5244d2bc16d4a77ad24c843ff685fc82b9c50d7f1284b0f6eeb658b949cf3b347c4ff6e188f3a04df281a10cda8f0dc9808d7440
      - TOKEN_REFRESH_URL=http://mc_auth:3005/refresh
      - MC_COMPONENT_URL=http://mc_component:3001
      - MC_USER_URL=http://mc_user:3002
      - MC_NOTIFICATION_URL=http://mc_notif:3003
      - MC_ORDER_URL=http://nginx/mc_order
      - MC_AUTH_URL=http://mc_auth:3005
      - MC_ARTICLE_URL=http://mc_article:3006
      - MC_MENU_URL=http://mc_menu:3008
      - MC_LOG_URL=http://mc_log:3009
      - MC_RESTAURANT_URL=http://mc_payment:3010
      - ALLOWED_ORIGIN=https://localhost:8080
    networks:
      - shared-net

networks:
  shared-net:
    external: true
